craftercms/video-center-blueprint

- readme.md
- site/website/search/index.xml
- sources/app/src/Router.js
- sources/app/src/components/VideoPlayer/VideoPlayer.js
Update on router, readme and loading of video in player
> Update on router, readme and loading of video in player

- config/engine/site-config.xml
* Added SPA configuration in site-config.xml, so that now any request to a page will return the /templates/web/entry.ftl.
> Added SPA configuration:

- config/studio/administration/config-list.xml
- config/studio/administration/samples/sample-form-control-rte-setup-tinymce5.xml
- config/studio/administration/site-config-tools.xml
- config/studio/content-types/component/stream/form-definition.xml
- config/studio/content-types/component/video/form-definition.xml
- config/studio/form-control-config/rte/rte-setup-tinymce5.xml
https://github.com/craftercms/craftercms/issues/2644
> [videocenter] Add the new RTE to the BP #2644

- config/studio/administration/samples/sample-site-config-tools.xml
- config/studio/administration/site-config-tools.xml
https://github.com/craftercms/craftercms/issues/2952
> [studio-ui] Add GraphiQL to Site Config #2952

- config/studio/role-mappings-config.xml
Fix role mappings
Git issue ticket:
https://github.com/craftercms/craftercms/issues/3022
> CRAFTERCMS-3022

- config/studio/administration/site-config-tools.xml
https://github.com/craftercms/craftercms/issues/2240
>  [studio-ui] Move "Log Console", "Logging Levels" to a global section in Studio #2240

- config/engine/application-context.xml
Aad valid xml file for engine application context config #2931
> Add valid xml file for engine application context config #2931

- config/studio/form-control-config/rte/rte-setup-tinymce5.xml
https://github.com/craftercms/craftercms/issues/3062
> [videocenter] Error message when editing content using TinyMCE5 control #3062

- config/studio/permission-mappings-config.xml
Repository API v2
https://github.com/craftercms/craftercms/issues/3070
> CRAFTERCMS-3070

- config/studio/studio_version.xml
- craftercms-plugin.yaml
https://github.com/craftercms/craftercms/issues/2775
Depends on https://github.com/craftercms/studio/pull/1610
> Update plugin descriptor format

- config/studio/administration/config-list.xml
- config/studio/permission-mappings-config.xml
Active environment feature
https://github.com/craftercms/craftercms/issues/2587
> CRAFTERCMS-2587

- config/studio/context-nav/contextual-nav.xml
added quick create configuration
https://github.com/craftercms/craftercms/issues/3214
> CRAFTERCMS-3214

- config/studio/administration/site-config-tools.xml
- config/studio/workflow/notification-config.xml
Added notification config update for pull from remote with merge options
Added video transcoding datasource config
> CRAFTERCMS-2655;CRAFTERCMS-3231

- config/studio/administration/site-config-tools.xml
Updated upgrade manager pipeline
https://github.com/craftercms/craftercms/issues/3231
https://github.com/craftercms/craftercms/issues/3236
> CRAFTERCMS-3231;CRAFTERCMS-3236

- config/studio/workflow/notification-config.xml
> fixed merge issue

- config/studio/site-config.xml
https://github.com/craftercms/craftercms/issues/3328
> Add new property for studio extensions

- config/studio/permission-mappings-config.xml
Added permissions for resolve conflict APIs
> CRAFTERCMS-3381

- config/studio/permission-mappings-config.xml
added delete_content permission
> CRAFTERCMS-3446

- config/studio/permission-mappings-config.xml
https://github.com/craftercms/craftercms/issues/3420
> Update config file

- config/studio/permission-mappings-config.xml
added write_configuration permission for developer
> CRAFTERCMS-3427

- config/studio/administration/config-list.xml
https://github.com/craftercms/craftercms/issues/3430
> Update config file version

- config/studio/permission-mappings-config.xml
Added permissions for publishing queue API
> CRAFTERCMS-3429

- config/studio/content-types/component/stream/form-definition.xml
- config/studio/content-types/page/page-home/form-definition.xml
https://github.com/craftercms/craftercms/issues/3500
> Update blueprints to use new datasources

- config/engine/site-config.xml
- scripts/pages/page-home.groovy
- templates/web/entry.ftl
https://github.com/craftercms/craftercms/issues/3548
> [videocenter] Video Center preview doesnt work through HTTPs #3548

- config/studio/content-types/component/component-channel/config.xml
- config/studio/content-types/component/component-footer/config.xml
- config/studio/content-types/component/component-slider/config.xml
- config/studio/content-types/page/entry/config.xml
- config/studio/content-types/page/page-home/config.xml
Update content creation permission to limit where a content type can be created, say for streams, you can only create content type, `Stream`
> Update content creation permission

- config/studio/content-types/component/stream-origin/form-definition.xml
- config/studio/content-types/component/stream/form-definition.xml
- config/studio/content-types/component/video-on-demand/form-definition.xml
- config/studio/content-types/component/youtube-video/form-definition.xml
Add videos, streams and origin to quick create
> Add videos, streams and origin to quick create

- config/studio/administration/site-config-tools.xml
https://github.com/craftercms/craftercms/issues/3802
> Remove deprecated datasource

- config/studio/content-types/component/stream-origin/config.xml
- config/studio/content-types/component/stream/config.xml
- config/studio/content-types/component/video-on-demand/config.xml
- config/studio/content-types/component/youtube-video/config.xml
Update config.xml with missing quickcreate values #4163
> Update config.xml with missing quickcreate values #4163

- config/studio/form-control-config/rte/rte-setup-tinymce5.xml
- craftercms-plugin.yaml
https://github.com/craftercms/craftercms/issues/4509
> [4509] RTE wrap for long lines of code or text

- sources/app/yarn.lock
Upgrade based on https://github.com/craftercms/video-center-blueprint/pull/149
> [next] build(deps): bump tar from 4.4.13 to 4.4.15 in /sources/app

- sources/app/src/components/Header/Header.js
https://github.com/craftercms/craftercms/issues/4723
> [4723][next] Remove the "Fork me on Github" banner from the Video-Center Blueprint to the UI

- craftercms-plugin.yaml
- sources/app/src/components/Header/Header.js
https://github.com/craftercms/craftercms/issues/4723
> [4723][3.1.x] Remove the "Fork me on Github" banner from the Video-Center Blueprint to the UI

- config/studio/ui.xml
- craftercms-plugin.yaml
- sources/app/src/components/Cards/Cards.js
- sources/app/src/utils.js
- sources/app/yarn.lock
- bump simple-get from 3.1.0 to 3.1.1 in /sources/app
- bump follow-redirects from 1.13.0 to 1.14.7 in /sources/app
- Use the same icon for Site Tools in Sidebar and Navigation Menu #5308
https://github.com/craftercms/craftercms/issues/5263
> [5263][next] Video Center View All videos for a channel does not reflect the total amount of videos

- config/studio/site-config.xml
- craftercms-plugin.yaml
https://github.com/craftercms/craftercms/issues/5427
https://github.com/craftercms/craftercms/issues/5425
> Update config for protected folders

- craftercms-plugin.yaml
- site/videos/black-eye-galaxy-m64.xml
- site/videos/chemistry-of-concrete.xml
- site/videos/epigenetics.xml
- site/videos/godels-incompleteness-theorem.xml
- site/videos/goldbach-conjecture.xml
- site/videos/how-much-caffeine-in-coffee.xml
- site/videos/how-restaurants-use-psychology-to-make-you-spend-more-money.xml
- site/videos/james-webb-space-telescope.xml
- site/videos/lift-and-wings.xml
- site/videos/light-bulb-in-hydrofluoric-acid-hf.xml
- site/videos/sha-secure-hashing-algorithm.xml
- site/videos/the-engineering-of-the-drinking-bird.xml
- site/videos/the-incredible-inventions-of-intuitive-ai.xml
- site/videos/the-ingenious-design-of-the-aluminum-beverage-can.xml
- site/videos/the-psychology-of-evil.xml
- site/videos/why-c-is-so-influential.xml
- site/videos/why-do-we-have-earwax.xml
- site/videos/why-is-glass-transparent.xml
- site/videos/will-stress-really-make-you-go-gray.xml
- site/videos/x-rays-from-messier-80.xml
- Remove stale properties
https://github.com/craftercms/craftercms/issues/5752
> [5752] Blueprint updates

- config/studio/administration/site-config-tools.xml
- config/studio/content-types/component/stream/form-definition.xml
- config/studio/content-types/component/video-on-demand/form-definition.xml
- config/studio/content-types/component/youtube-video/form-definition.xml
https://github.com/craftercms/craftercms/issues/5785
> Update datasource components and simpleTaxonomy
